### ISSUE TITLE
GNOME: allow payment by PayPal if cash was selected

### ISSUE THREAD

**Issue by kittykat** [puiterwijk/regcfp#145]
At the moment, if one select cash payment, then one can no longer pay by PayPal before the event.

Cash payments should only delay the payment at the latest until the badge is picked up, but should still allow the user to change their mind and pay by PayPal.

**Comment by ghost** [comment]
Fixed as part of #167 in https://github.com/puiterwijk/regcfp/pull/167/commits/d976ca57bd492fbdf0f4b6975b7f3a89d9231622 -- the "Pay more" option will now let you decide whether you still want to pay the registration fee at the conference, or whether you want to pay it now with PayPal.
