### ISSUE TITLE
Mozilla is shutting down Persona

### ISSUE THREAD

**Issue by ghost** [puiterwijk/regcfp#156]
The Persona system is being shut down at the end of November: https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers

Any thoughts on how we should fix this for next year's conferences?

**Comment by puiterwijk** [comment]
I am working on new code for regcfp to deal with this.
I do not yet have a schedule, but if you have any conferences planned, I can take that into consideration for the scheduling there.

**Comment by puiterwijk** [comment]
(that was one of the main goals of making the auth stuff modular :) )

**Comment by ghost** [comment]
OK cool. I'm thinking about GUADEC 2017, which ideally we'd be able to start doing registration for in a couple of months because we have quite early accommodation booking deadlines this year. I can help with coding if you're short of time. What providers are you thinking of using instead of Persona?

**Comment by puiterwijk** [comment]
Ah, cool. Feel free to ping me on IRC then (puiterwijk on both Freenode and GIMPNet).
I am planning to use a specific provider that I'm now setting up myself, that will federate to the major social networks and also GNOME/Fedora accounts (as well as some other sources).
