### ISSUE TITLE
When registration, not sure how to write country name

### ISSUE THREAD

**Issue by mairin** [puiterwijk/regcfp#18]
There's a blank text field for country in registration but I think it would be nicer to have a auto complete in the field. (I'm not sure if USA or US or United States is preferred, for example.)

It also seems like the check for country name is stricter when you first register than when you edit your registration. I was able to enter "murica" as my country and it was accepted.

**Comment by stickster** [comment]
via https://www.npmjs.com/package/country-data perhaps?
