### ISSUE TITLE
Registration link is wrong in panel

### ISSUE THREAD

**Issue by mairin** [puiterwijk/regcfp#19]
I'm logged in and at the main panel / registration home page. At the bottom in the admin section there is a link to "List all Registrations." If I click on it, it takes me to http://example.com:4000/registration/admin/list which 404s. The link http://example.com:4000/registration/list works though and has the registration list. So I think the button has the 'admin' added to the URL which is incorrect?

**Comment by puiterwijk** [comment]
No, the link to /admin/registration is a different one that also shows private ones that got lost.
