### ISSUE TITLE
Handle scaled registration fee

### ISSUE THREAD

**Issue by stickster** [puiterwijk/regcfp#199]
So the Council is looking to have a scaled registration fee, where the fee would be a similarly "reasonable" cost in various locations. IOW, not simply an equivalent in USD. This would be a great way to go: http://bigmacindex.org/

Also tagging @mattdm here so he knows which way this is going.

**Comment by stickster** [comment]
This probably also affects issue #198.

**Comment by mattdm** [comment]
We were thinking of a baseline $25 US, btw.

**Comment by bexelbie** [comment]
This and #198 will need to tie into a billing/payment methodology.  I should have more details early next week about how this will work.  I envision a three step process:

1. Register via the system, including all funding/etc. issues
2. Get an email with the payment link and amount confirmation.
3. Registrant either:
a) Pays - possibly with a date as payments will most likely be non-refundable
b) cancels their registration before paying
c) is auto-cancelled (can be a human driven thing) if they don't pay by a certain date (date tbd)
d) pays, then cancels

**Comment by puiterwijk** [comment]
@bexelbie Do you have the information yet that you thought to be getting?

Is there any reason we want the registration and payment steps separate, and not at the same time?
