### ISSUE TITLE
Custom user registration fields

### ISSUE THREAD

**Issue by stickster** [puiterwijk/regcfp#5]
It would be helpful to be able to add custom fields with user details. These should be optionally visible for registration. A field should be able to offer a single-choice value, multiple-choice value, or text. If a user can edit their own registration, any new registration-visible fields should be fillable until registration is locked.

Fields should also have an option of being visible to all, only visible to registrant+admin, or admin only.

**Comment by stickster** [comment]
Examples for using this feature:
- meal preferences
- t-shirt size
- country of origin (registrant + admin only, some don't want this published)

**Comment by puiterwijk** [comment]
The first version will have the defined fields in the configuration file.
If you want this from some sort of admin panel, I can add that later.
